# Generated by Django 4.2.7 on 2023-12-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_teacher_student_rollnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='imageUrl',
            field=models.CharField(default='', max_length=200),
        ),
    ]
